prefix d:<http://www.semanticweb.org/athal/ontologies/2024/4/laptop#>

SELECT ?LaptopBrand ?LaptopModel ?LaptopPrice ?OSName ?ProcessorName ?GPUName ?RAMType ?RAMSize ?StorageType ?StorageSize
WHERE {
?lptp	d:LaptopBrand ?LaptopBrand;
		d:LaptopModel ?LaptopModel;
		d:LaptopPrice ?LaptopPrice;
		d:hasOS ?os;
  		d:hasProcessor ?prc;
    	d:hasGPU ?gpu;
     	d:hasRAM ?ram;
      	d:hasStorage ?strg.
?os		d:OSName ?OSName.
?prc	d:ProcessorName ?ProcessorName.
?gpu	d:GPUName ?GPUName.
?ram	d:RAMType ?RAMType;
     	d:RAMSize ?RAMSize.
?strg	d:StorageType ?StorageType;
      	d:StorageSize ?StorageSize.
}